# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ForQualification' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ForQualification

  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'SDWebImage', '~> 5.0'
  pod 'PKHUD', '~> 5.0'
  pod 'Firebase/DynamicLinks'

  target 'ForQualificationTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase'
  end

  target 'ForQualificationUITests' do
    # Pods for testing
  end

end
